name: 检查直播源链接

on:
  workflow_dispatch: # 允许手动运行
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点运行

permissions:
  contents: write # 授予写入仓库内容的权限

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Git 配置
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 运行检查脚本
        run: python main.py

      - name: 提交更改（如果存在）
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新播放链接数据"
          file_pattern: results.txt

      - name: 强制推送更改
        run: git push origin main --force
