name: 自动清理 Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '25 22 * * *'

permissions:
  actions: write
  contents: read

jobs:
  clean-runs:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装最新版 GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: 删除 workflow 运行历史
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          export GH_TOKEN=${GH_TOKEN}
          LIMIT=50
          REPO=${{ github.repository }}
          echo "当前可见的 workflow run："
          gh run list --repo "$REPO" --limit $LIMIT --json databaseId,status,headBranch,event,name --jq '.[] | "\(.databaseId) \(.status) \(.headBranch) \(.event) \(.name)"'
          while true; do
            RUN_IDS=$(gh run list --repo "$REPO" --limit $LIMIT --json databaseId --jq '.[].databaseId')
            if [ -z "$RUN_IDS" ]; then
              break
            fi
            for id in $RUN_IDS; do
              echo "准备删除 run id: $id"
              yes | gh run delete "$id" --repo "$REPO"
              sleep 1
            done
            if [ "$(echo "$RUN_IDS" | wc -l)" -lt "$LIMIT" ]; then
              break
            fi
          done
